version: '3'

services:
  torrent-indexer:
    image: thanegche/torrent-indexerteste:latest
    container_name: torrent-indexer
    restart: unless-stopped
    ports:
      - 8081:7006
    networks:
      - indexer
    environment:
      - REDIS_HOST=redis
  
  redis:
    image: redis:alpine
    container_name: redis
    restart: unless-stopped
    networks:
      - indexer

networks:
  indexer:
